dh_chains:
    torso_chain:
        dh:
            # theta, alpha, a, d
            - [ 0, 0, 0, 0 ] # torso_lower_neck_tilt_joint
            - [ 0, 0, 0, 0 ] # torso_pan_joint
            - [ 0, 0, 0, 0 ] # torso_upper_neck_tilt_joint
        gearing: [ 0, 0, 0 ]

    arm_chain:
        dh:
            # theta, alpha, a, d
            - [ 0, 0, 0, 0 ] # joint arm_0_link -> arm_1_link
            - [ 0, 0, 0, 0 ] # joint arm_1_link -> arm_2_link
            - [ 0, 0, 0, 0 ] # joint arm_2_link -> arm_3_link
            - [ 0, 0, 0, 0 ] # joint arm_3_link -> arm_4_link
            - [ 0, 0, 0, 0 ] # joint arm_4_link -> arm_5_link
            - [ 0, 0, 0, 0 ] # joint arm_5_link -> arm_6_link
            - [ 0, 0, 0, 0 ] # joint arm_6_link -> arm_7_link
        gearing: [ 0, 0, 0, 0, 0, 0, 0 ]

transforms:
    base_footprint_joint:            [ 0, 0, 0, 0, 0, 0 ]
    arm_cb:                          [ 1, 1, 1, 1, 1, 1 ]
    
    torso_0_joint:                   [ 0, 0, 0, 0, 0, 0 ]
    arm_0_joint:                     [ 0, 0, 0, 0, 0, 0 ]   # joint base_link -> arm_0_link

    head_axis_joint:                 [ 0, 0, 0, 0, 0, 0 ]   # torso_upper_neck_tilt_link -> head_axis_link
    head_color_camera_l_joint:       [ 1, 1, 1, 1, 1, 1 ]   # head_axis_link -> head_color_camera_l_link
    head_color_camera_r_joint:       [ 0, 0, 0, 0, 0, 0 ]   # head_axis_link -> head_color_camera_r_link
    head_cam3d_rgb_optical_frame_joint: [ 1, 1, 1, 1, 1, 1 ] # head_color_camera_l_link -> head_cam3d_rgb_optical_frame

    head_color_camera_l_frame_joint: [ 0, 0, 0, 0, 0, 0 ]   # head_color_camera_l_link -> head_color_camera_l_frame

rectified_cams:
    left:
        baseline_shift: 0
        f_shift: 0
        cx_shift: 0
        cy_shift: 0
    right:
        baseline_shift: 1
        f_shift: 0
        cx_shift: 0
        cy_shift: 0
    kinect_rgb:
        baseline_shift: 0
        f_shift: 0
        cx_shift: 0
        cy_shift: 0

checkerboards:
    cb_9x6:
        spacing_x: 0
        spacing_y: 0
