camera_chains:
  - sensor_id: left
    camera_id: left
    chain:
        before_chain: [ base_footprint_joint, torso_0_joint ]
        chain_id: torso_chain
        dh_link_num: 3
        after_chain: [ head_axis_joint, head_color_camera_l_joint ]
  - sensor_id: right
    camera_id: right
    chain:
        before_chain: [ base_footprint_joint, torso_0_joint ]
        chain_id: torso_chain
        dh_link_num: 3
        after_chain: [ head_axis_joint, head_color_camera_l_joint ]
  - sensor_id: kinect_rgb
    camera_id: kinect_rgb
    chain:
        before_chain: [ base_footprint_joint, torso_0_joint ]
        chain_id: torso_chain
        dh_link_num: 3
        after_chain: [ head_axis_joint, head_cam3d_rgb_optical_frame_joint ]

chains:
  - sensor_id:    arm_chain
    before_chain: [ base_footprint_joint, arm_0_joint ]
    chain_id:     arm_chain
    after_chain:  [ arm_cb ]
    dh_link_num:  7

