dh_chains:
    torso_chain:
        dh:
            #   theta, alpha, a,  d
            - [ 0,     pi/2,  0,  0      ] # torso_lower_neck_tilt_joint
            - [ 0,     -pi/2, 0, -0.2565 ] # torso_pan_joint
            - [ 0,     0,     0,  0      ] # torso_upper_neck_tilt_joint # new urdf
        cov:
            joint_angles: [ 0.01, 0.01, 0.01 ]
        gearing: [ 1.0, 1.0, 1.0 ]
        
    arm_chain:
        dh:
            #   theta,    alpha, a, d
            - [ -2.8407,  pi/2,  0, 0.1915  ]      # joint arm_0_link -> arm_1_link
            - [ 0,       -pi/2,  0, 0       ]      # joint arm_1_link -> arm_2_link
            - [ pi,       pi/2,  0, 0.4     ]      # joint arm_2_link -> arm_3_link
            - [ 0,       -pi/2,  0, 0       ]      # joint arm_3_link -> arm_4_link
            - [ pi,       pi/2,  0, 0.39    ]      # joint arm_4_link -> arm_5_link
            - [ 0,       -pi/2,  0, 0       ]      # joint arm_5_link -> arm_6_link
            - [ 0,        0,     0, 0.057   ]      # joint arm_6_link -> arm_7_link
        cov:
            joint_angles: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
        gearing: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]

transforms:
    # specified as x,y,z translation and rotation vector (angle = magnitude, direction = vector)!
    base_footprint_joint: [ 0, 0, 0, 0, 0, 0 ]
    arm_cb:               [ -0.12, 0.02, 0.1, pi/2, 0, 0 ]
    
    head_axis_joint:      [ 0, .173, 0, 0, 0, 0 ]                                                 # rpy: (0, 0, 0)                # torso_upper_neck_tilt_link -> head_axis_link # new urdf
    head_color_camera_l_joint: [ 0, 0, -0.06, 0, -pi/2, 0]                                        # rpy: (pi, -pi/2, pi)          # head_axis_link -> head_color_camera_l_link
    head_color_camera_r_joint: [ 0, 0,  0.06, 0, -pi/2, 0]                                        # rpy: (pi, -pi/2, pi)          # head_axis_link -> head_color_camera_r_link
    head_color_camera_l_frame_joint: [ 0, 0, 0, 1.20919958, -1.20919958,  1.20919958 ]            # rpy: (-pi/2, -pi/2, -pi)      # head_color_camera_l_link -> head_color_camera_l_frame
    head_cam3d_rgb_optical_frame_joint: [ -0.002, -0.030, 0.020, 0, -pi/2, 0 ]                    # rpy: (0, -pi/2, 0)            # head_color_camera_l_link -> head_cam3d_rgb_optical_frame
    
    torso_0_joint:        [ 0.155, 0, 0.892, pi/2, 0, 0]                                          # rpy: (pi/2, 0, 0)             # base_link -> torso_lower_neck_tilt_joint
    arm_0_joint:          [-0.015982, -0.080992, 0.875995, 0.78081498, -0.10279649, -0.24817203 ] # rpy: (0.7854, 0.0, -0.2618)   # base_link -> arm_0_link
    
rectified_cams:
    left:
        baseline_shift: 0.0
        f_shift: 0.0
        cx_shift: 0.0
        cy_shift: 0.0
        cov: {u: 0.125, v: 0.125}
    right:
        baseline_shift: 0.0
        f_shift: 0.0
        cx_shift: 0.0
        cy_shift: 0.0
        cov: {u: 0.125, v: 0.125}
    kinect_rgb:
        baseline_shift: 0.0
        f_shift: 0.0
        cx_shift: 0.0
        cy_shift: 0.0
        cov: {u: 0.25, v: 0.25}    

checkerboards:
    cb_9x6:
      corners_x: 9
      corners_y: 6
      spacing_x: .03
      spacing_y: .03
